
package main.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientAdapterImplService", targetNamespace = "http://endpoint.main/", wsdlLocation = "http://localhost:8080/WS/Test?wsdl")
public class ClientAdapterImplService
    extends Service
{

    private final static URL CLIENTADAPTERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTADAPTERIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTADAPTERIMPLSERVICE_QNAME = new QName("http://endpoint.main/", "ClientAdapterImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTADAPTERIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTADAPTERIMPLSERVICE_EXCEPTION = e;
    }

    public ClientAdapterImplService() {
        super(__getWsdlLocation(), CLIENTADAPTERIMPLSERVICE_QNAME);
    }

    public ClientAdapterImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTADAPTERIMPLSERVICE_QNAME, features);
    }

    public ClientAdapterImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTADAPTERIMPLSERVICE_QNAME);
    }

    public ClientAdapterImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTADAPTERIMPLSERVICE_QNAME, features);
    }

    public ClientAdapterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientAdapterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientAdapterImpl
     */
    @WebEndpoint(name = "ClientAdapterImplPort")
    public ClientAdapterImpl getClientAdapterImplPort() {
        return super.getPort(new QName("http://endpoint.main/", "ClientAdapterImplPort"), ClientAdapterImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientAdapterImpl
     */
    @WebEndpoint(name = "ClientAdapterImplPort")
    public ClientAdapterImpl getClientAdapterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.main/", "ClientAdapterImplPort"), ClientAdapterImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTADAPTERIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTADAPTERIMPLSERVICE_EXCEPTION;
        }
        return CLIENTADAPTERIMPLSERVICE_WSDL_LOCATION;
    }

}
