
package main.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IClientAdapter", targetNamespace = "http://endpoint.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IClientAdapter {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saySomething", targetNamespace = "http://endpoint.main/", className = "main.endpoint.SaySomething")
    @ResponseWrapper(localName = "saySomethingResponse", targetNamespace = "http://endpoint.main/", className = "main.endpoint.SaySomethingResponse")
    @Action(input = "http://endpoint.main/IClientAdapter/saySomethingRequest", output = "http://endpoint.main/IClientAdapter/saySomethingResponse")
    public String saySomething(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
